name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Firebase
        run: npm install -g firebase-tools
      - name: Publicar Site
        run: firebase deploy --only hosting --project w3gestor --token "${{ secrets.FIREBASE_TOKEN }}"
